name = "tasks-app"
main = "src/app.ts"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tasks-app"
database_id = "000-000-000-000"
migrations_dir = "src/db/migrations"

[vars]
LOG_LEVEL = "debug"
GITHUB_CLIENT_ID = "Ov23liQmZg6X2B02AyTa"
GITHUB_CLIENT_SECRET = "5b5163f26a066cb32ea4c48579154c456ce0c147"
AUTH_SECRET = "secret"
AUTH_URL = "http://localhost:5173/api/auth"
